### ISSUE TITLE
安装运行

### ISSUE THREAD

**Issue by lalawinter** [CXavireH/ORB_SLAM3_with_dense_pointcloud#1]
请问下这个也是带yolo检测吗？这个安装步骤和ORB_SLAM3一样吗？运行指令方便写详细点不

**Comment by CXavireH** [comment]
> 请问下这个也是带yolo检测吗？这个安装步骤和ORB_SLAM3一样吗？运行指令方便写详细点不

yolo检测部署在这个项目里但是根据需要，后面的版本都注释了。
运行指令在代码中有help  可以看example中的代码
